refresh_alarm_status:
  name: Refresh the status of the alarm.
  description: Make a request to check the status of the alarm.
  fields:
    instalation_id:
      name: Instalation Id
      description: The instalation id of the alarm.
      required: true
      example: Instalation id.